GET  http://127.0.0.1:8000/api/music_instruments?name=mad&page=1
Accept: application/json

###
GET http://api.themoviedb.org/3/search/movie?api_key=09ba10d7db39957f5036cc083426ef3a&language=fr&query=bl&page=1
